### ISSUE TITLE
Please switch to using an __init__.py file as per convention for ComfyUI-Manager et al.

### ISSUE THREAD

**Issue by daniel-lewis-ab** [tudal/Hakkun-ComfyUI-nodes#2]
The vast majority of nodepacks use __init__.py to declare node class mappings and such.  This is a request to have that convention followed so your pack is more compatible with other nodepacks and tools.

Thanks so much.  :)

**Comment by tudal** [comment]
Sure I can add __init__.py to repository. But what about fact that my whole node is not as folder but just one .py file in ```custom_nodes``` (no ide how that happend)? Sorry I'm clueless ;)
If theres second file there should be a folder xd

**Comment by daniel-lewis-ab** [comment]
It's not actually necessary.  It's just that alot of automated tools check __init__.py specifically as an entry point to pull the node class and name mappings, including ComfyUI-Manager and some of our own tools.  It's become a defacto standard for node packs.

**Comment by tudal** [comment]
Like this?
